config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  get "/tasks", to: "tasks#index"
  # create task
  get "/tasks/new", to: "tasks#new",  as: :new_task
  post "/tasks", to: "tasks#create"
  # show
  get "/tasks/:id", to: "tasks#show", as: :task
  # edit task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  # delete task
  delete "tasks/:id", to: "tasks#destroy", as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

def task_params
  params.require(:task).permit(:title, :details, :completed)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Task Manager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container mt-5">
<%= form_with model: @task, class: "card p-4" do |f| %>
<div class="mb-3">
  <%= f.label :title, class: 'form-label' %>
  <%= f.text_field :title, class: 'form-control'%>
  </div>
  <div class="mb-3">
  <%= f.label :details, class: 'form-label' %>
  <%= f.text_field :details, class: 'form-control' %>
  </div>
  <%= f.submit "Validate", class: "btn btn-primary" %>
<% end %>
</div>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="container mt-5">
  <div class="text-center">
    <h1> Welcome </h1>
  </div>

  <ul class="list-group">
    <% @tasks.each do |task| %>
      <li class="list-group-item d-flex justify-content-between align-items-center position-relative">
        <a href="<%= task_path(task) %>" class="text-dark text-decoration-none flex-grow-1">
          <div class="fw-bold"><%= task.title %></div>
          <small class="text-muted"><%= task.details %></small>
        </a>
        <%= link_to delete_path(task), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm position-absolute end-0 me-3" do %>
        <i class="fa-solid fa-trash"></i>
        <% end %>
      </li>
    <% end %>
  </ul>
    <%= link_to new_task_path, class: "btn btn-primary btn-sm end-0 mt-1" do %>
      <i class="fa-solid fa-plus"> Add a new task</i>
    <% end %>
</div>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<div class="container mt-5">
<div class="card">
  <h5 class="card-header">Task</h5>
  <div class="card-body">
    <h5 class="card-title"><%= @task.title %></h5>
    <p class="card-text"><%= @task.details %></p>
    <%= link_to tasks_path, class: "btn btn-primary btn-sm mt-1" do %>
      <i class="fa-solid fa-list"> List</i>
    <% end %>
    <%= link_to edit_task_path, class: "btn btn-warning btn-sm end-0 mt-1" do %>
      <i class="fa-solid fa-pen-to-square"> Edit</i>
    <% end %>
  </div>
</div>
</div>